# Generated by Django 3.0.4 on 2020-05-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0003_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Picture',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
