# Generated by Django 3.0.4 on 2020-05-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0004_auto_20200501_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Picture',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
