# Generated by Django 3.0.4 on 2020-05-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0005_auto_20200502_0433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categorie', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Offer', models.CharField(max_length=50)),
                ('Bedrooms', models.IntegerField()),
                ('Bathrooms', models.IntegerField()),
                ('Area', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='categorie',
            name='Type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='citie',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='Discount',
            field=models.CharField(max_length=50),
        ),
    ]
