# Generated by Django 3.0.4 on 2020-05-03 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0006_auto_20200503_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='option',
            name='Bathrooms',
        ),
        migrations.RemoveField(
            model_name='option',
            name='Bedrooms',
        ),
        migrations.RemoveField(
            model_name='option',
            name='Categorie',
        ),
        migrations.RemoveField(
            model_name='option',
            name='Offer',
        ),
    ]
