# Generated by Django 3.0.4 on 2020-05-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0007_auto_20200504_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='Area',
            field=models.CharField(default='Area', max_length=50),
        ),
        migrations.AddField(
            model_name='option',
            name='Bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='Bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='option',
            name='Categorie',
            field=models.CharField(default='Categorie', max_length=50),
        ),
        migrations.AddField(
            model_name='option',
            name='Offer',
            field=models.CharField(default='Offer', max_length=50),
        ),
        migrations.AlterField(
            model_name='option',
            name='City',
            field=models.CharField(default='City', max_length=50),
        ),
    ]
