# Generated by Django 3.0.4 on 2020-05-04 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0009_auto_20200504_0454'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.AddField(
            model_name='property',
            name='Price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='Title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='Bathrooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bathrooms', to='dealer.Bathroom'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Bedrooms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bedrooms', to='dealer.Bedroom'),
        ),
    ]
