# Generated by Django 3.0.4 on 2020-05-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0010_auto_20200505_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Picture',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='Title',
        ),
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
