# Generated by Django 3.0.4 on 2020-05-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0011_auto_20200514_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
