# Generated by Django 3.0.4 on 2020-05-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0012_auto_20200514_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Price_unit',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
