# Generated by Django 3.0.4 on 2020-05-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0013_auto_20200514_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Price_unit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
