# Generated by Django 3.0.4 on 2020-05-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0016_auto_20200514_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
